### ISSUE TITLE
Inappropriate value for attribute "subnets" with Terraform version 0.12

### ISSUE THREAD

**Issue by jessie00chen** [trussworks/terraform-aws-alb-web-containers#18]
Trying to use Terraform 0.12.3 with alb-web-containers/aws and ran into below errors.
Any plans to make this module compatible with 0.12.* ?

```
source  = "trussworks/alb-web-containers/aws"
version = "~> 2.4.0"
```

```
Error: Incorrect attribute value type

  on .terraform/modules/app_ellsworth.alb_web_containers/trussworks-terraform-aws-alb-web-containers-ac86ff1/main.tf line 90, in resource "aws_lb" "main":
  90:   subnets         = ["${var.alb_subnet_ids}"]

Inappropriate value for attribute "subnets": element 0: string required.
```

**Comment by brainsik** [comment]
Hi, Jessie! :-)

We definitely will migrate this to work with 0.12. Unfortunately, the nature of this particular issue means it is not possible to make the code compatible with both 0.11 and 0.12 and will require a hard cut to 0.12 syntax. This is something we definitely will do, but I don't have a timeline for that yet. At the moment, we're migrating modules that can be compatible with both 0.11 and 0.12. We'll circle back around when that is done.

**Comment by jessie00chen** [comment]
Thanks for the quick response Jeremy!

**Comment by dynamike** [comment]
https://github.com/trussworks/terraform-aws-alb-web-containers/releases/tag/v3.0.0 now support Terraform 0.12. Let us know if you run into issues.
